spring:
  profiles:
    active:  dev
---
server:
  port: 8201
spring:
  profiles:
    application:
      name:  springcloud-provider-dept
      
eureka:
  clent:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
server:
  port: 8202
spring:
  profiles:
    application:
      name: springcloud-provider-dept
      
eureka:
  clent:
    service-url:
      defaultZone:http://eureka7002.com:7002/eureka/